// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Zoo.Data;

#nullable disable

namespace Zoo.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20240414070922_InicioBBDD")]
    partial class InicioBBDD
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0-preview.1.24081.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Zoo.Models.Arraza", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("Deskribapena")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("ID_lekua")
                        .HasColumnType("int");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Izena")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.HasIndex("ID_lekua");

                    b.ToTable("Arrazak");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            Deskribapena = "Donec ante enim, imperdiet non metus a, aliquet fermentum tortor. Etiam sem nunc, ornare id dignissim non, congue at nulla. Integer semper leo nisl, ac tincidunt libero aliquam id. Morbi quis ornare eros. Nunc at ultricies mi. Aliquam vitae bibendum metus. Aenean venenatis cursus sapien. Vivamus feugiat egestas urna.",
                            ID_lekua = 1,
                            ImageUrl = "",
                            Izena = "Tigre"
                        },
                        new
                        {
                            ID = 2,
                            Deskribapena = "Donec ante enim, imperdiet non metus a, aliquet fermentum tortor. Etiam sem nunc, ornare id dignissim non, congue at nulla. Integer semper leo nisl, ac tincidunt libero aliquam id. Morbi quis ornare eros. Nunc at ultricies mi. Aliquam vitae bibendum metus. Aenean venenatis cursus sapien. Vivamus feugiat egestas urna.",
                            ID_lekua = 2,
                            ImageUrl = "",
                            Izena = "Leon"
                        },
                        new
                        {
                            ID = 3,
                            Deskribapena = "Donec ante enim, imperdiet non metus a, aliquet fermentum tortor. Etiam sem nunc, ornare id dignissim non, congue at nulla. Integer semper leo nisl, ac tincidunt libero aliquam id. Morbi quis ornare eros. Nunc at ultricies mi. Aliquam vitae bibendum metus. Aenean venenatis cursus sapien. Vivamus feugiat egestas urna.",
                            ID_lekua = 3,
                            ImageUrl = "",
                            Izena = "Pato"
                        },
                        new
                        {
                            ID = 4,
                            Deskribapena = "Donec ante enim, imperdiet non metus a, aliquet fermentum tortor. Etiam sem nunc, ornare id dignissim non, congue at nulla. Integer semper leo nisl, ac tincidunt libero aliquam id. Morbi quis ornare eros. Nunc at ultricies mi. Aliquam vitae bibendum metus. Aenean venenatis cursus sapien. Vivamus feugiat egestas urna.",
                            ID_lekua = 4,
                            ImageUrl = "",
                            Izena = "Panda"
                        },
                        new
                        {
                            ID = 5,
                            Deskribapena = "Donec ante enim, imperdiet non metus a, aliquet fermentum tortor. Etiam sem nunc, ornare id dignissim non, congue at nulla. Integer semper leo nisl, ac tincidunt libero aliquam id. Morbi quis ornare eros. Nunc at ultricies mi. Aliquam vitae bibendum metus. Aenean venenatis cursus sapien. Vivamus feugiat egestas urna.",
                            ID_lekua = 5,
                            ImageUrl = "",
                            Izena = "Conejo"
                        },
                        new
                        {
                            ID = 6,
                            Deskribapena = "Donec ante enim, imperdiet non metus a, aliquet fermentum tortor. Etiam sem nunc, ornare id dignissim non, congue at nulla. Integer semper leo nisl, ac tincidunt libero aliquam id. Morbi quis ornare eros. Nunc at ultricies mi. Aliquam vitae bibendum metus. Aenean venenatis cursus sapien. Vivamus feugiat egestas urna.",
                            ID_lekua = 2,
                            ImageUrl = "",
                            Izena = "Delfin"
                        });
                });

            modelBuilder.Entity("Zoo.Models.Lekua", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("Deskribapena")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Izena")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("Lekuak");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            Deskribapena = "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed blandit vitae nunc vel consequat. Nulla euismod ex arcu, id ullamcorper nisi consequat ac. Fusce porta libero erat, sit amet fermentum libero ultricies feugiat. Mauris varius placerat accumsan. Aenean ornare orci quis arcu varius sagittis. Mauris rutrum augue vel ex aliquam, quis molestie dui rutrum. Sed vel augue iaculis metus imperdiet blandit in in justo. Sed efficitur leo at ornare varius. Nullam tincidunt nisl id ultrices convallis. Morbi volutpat turpis at ligula finibus, vel tincidunt mauris bibendum. Nullam auctor tellus quis porta ornare.",
                            Izena = "Interior1"
                        },
                        new
                        {
                            ID = 2,
                            Deskribapena = "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed blandit vitae nunc vel consequat. Nulla euismod ex arcu, id ullamcorper nisi consequat ac. Fusce porta libero erat, sit amet fermentum libero ultricies feugiat. Mauris varius placerat accumsan. Aenean ornare orci quis arcu varius sagittis. Mauris rutrum augue vel ex aliquam, quis molestie dui rutrum. Sed vel augue iaculis metus imperdiet blandit in in justo. Sed efficitur leo at ornare varius. Nullam tincidunt nisl id ultrices convallis. Morbi volutpat turpis at ligula finibus, vel tincidunt mauris bibendum. Nullam auctor tellus quis porta ornare.",
                            Izena = "Interior2"
                        },
                        new
                        {
                            ID = 3,
                            Deskribapena = "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed blandit vitae nunc vel consequat. Nulla euismod ex arcu, id ullamcorper nisi consequat ac. Fusce porta libero erat, sit amet fermentum libero ultricies feugiat. Mauris varius placerat accumsan. Aenean ornare orci quis arcu varius sagittis. Mauris rutrum augue vel ex aliquam, quis molestie dui rutrum. Sed vel augue iaculis metus imperdiet blandit in in justo. Sed efficitur leo at ornare varius. Nullam tincidunt nisl id ultrices convallis. Morbi volutpat turpis at ligula finibus, vel tincidunt mauris bibendum. Nullam auctor tellus quis porta ornare.",
                            Izena = "Sabana"
                        },
                        new
                        {
                            ID = 4,
                            Deskribapena = "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed blandit vitae nunc vel consequat. Nulla euismod ex arcu, id ullamcorper nisi consequat ac. Fusce porta libero erat, sit amet fermentum libero ultricies feugiat. Mauris varius placerat accumsan. Aenean ornare orci quis arcu varius sagittis. Mauris rutrum augue vel ex aliquam, quis molestie dui rutrum. Sed vel augue iaculis metus imperdiet blandit in in justo. Sed efficitur leo at ornare varius. Nullam tincidunt nisl id ultrices convallis. Morbi volutpat turpis at ligula finibus, vel tincidunt mauris bibendum. Nullam auctor tellus quis porta ornare.",
                            Izena = "Lago"
                        },
                        new
                        {
                            ID = 5,
                            Deskribapena = "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed blandit vitae nunc vel consequat. Nulla euismod ex arcu, id ullamcorper nisi consequat ac. Fusce porta libero erat, sit amet fermentum libero ultricies feugiat. Mauris varius placerat accumsan. Aenean ornare orci quis arcu varius sagittis. Mauris rutrum augue vel ex aliquam, quis molestie dui rutrum. Sed vel augue iaculis metus imperdiet blandit in in justo. Sed efficitur leo at ornare varius. Nullam tincidunt nisl id ultrices convallis. Morbi volutpat turpis at ligula finibus, vel tincidunt mauris bibendum. Nullam auctor tellus quis porta ornare.",
                            Izena = "Bosque"
                        });
                });

            modelBuilder.Entity("Zoo.Models.Arraza", b =>
                {
                    b.HasOne("Zoo.Models.Lekua", "Lekua")
                        .WithMany()
                        .HasForeignKey("ID_lekua");

                    b.Navigation("Lekua");
                });
#pragma warning restore 612, 618
        }
    }
}
