// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Zoo.Data;

#nullable disable

namespace Zoo.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20240430072309_lastmig")]
    partial class lastmig
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0-preview.1.24081.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasMaxLength(13)
                        .HasColumnType("nvarchar(13)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);

                    b.HasDiscriminator<string>("Discriminator").HasValue("IdentityUser");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("Zoo.Models.Animalia", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<int?>("ID_arraza")
                        .HasColumnType("int");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Izena")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateOnly>("Sarrera_data")
                        .HasColumnType("date");

                    b.Property<DateOnly>("urte_betetzea")
                        .HasColumnType("date");

                    b.HasKey("ID");

                    b.HasIndex("ID_arraza");

                    b.ToTable("Animaliak");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            ID_arraza = 1,
                            ImageUrl = "\\images\\animalia\\charlie.jpg",
                            Izena = "Charlie the Charming Chimpanzee",
                            Sarrera_data = new DateOnly(2022, 5, 15),
                            urte_betetzea = new DateOnly(2019, 3, 10)
                        },
                        new
                        {
                            ID = 2,
                            ID_arraza = 2,
                            ImageUrl = "\\images\\animalia\\goliath.jpg",
                            Izena = "Goliath the Gentle Giant Gorilla",
                            Sarrera_data = new DateOnly(2021, 10, 20),
                            urte_betetzea = new DateOnly(2018, 7, 5)
                        },
                        new
                        {
                            ID = 3,
                            ID_arraza = 3,
                            ImageUrl = "\\images\\animalia\\ruby.jpg",
                            Izena = "Ruby the Radiant Red Panda",
                            Sarrera_data = new DateOnly(2023, 1, 8),
                            urte_betetzea = new DateOnly(2020, 2, 15)
                        },
                        new
                        {
                            ID = 4,
                            ID_arraza = 4,
                            ImageUrl = "\\images\\animalia\\kenny.jpg",
                            Izena = "Kenny the Kicking Kangaroo",
                            Sarrera_data = new DateOnly(2020, 12, 3),
                            urte_betetzea = new DateOnly(2017, 9, 22)
                        },
                        new
                        {
                            ID = 5,
                            ID_arraza = 5,
                            ImageUrl = "\\images\\animalia\\sammy.jpg",
                            Izena = "Sammy the Sleepy Sloth",
                            Sarrera_data = new DateOnly(2023, 4, 25),
                            urte_betetzea = new DateOnly(2020, 10, 30)
                        },
                        new
                        {
                            ID = 6,
                            ID_arraza = 6,
                            ImageUrl = "\\images\\animalia\\aurora.jpg",
                            Izena = "Aurora the Agile Arctic Fox",
                            Sarrera_data = new DateOnly(2022, 8, 12),
                            urte_betetzea = new DateOnly(2019, 6, 18)
                        },
                        new
                        {
                            ID = 7,
                            ID_arraza = 7,
                            ImageUrl = "\\images\\animalia\\eleanor.jpg",
                            Izena = "Eleanor the Elegant Elephant",
                            Sarrera_data = new DateOnly(2021, 11, 30),
                            urte_betetzea = new DateOnly(2019, 4, 20)
                        },
                        new
                        {
                            ID = 8,
                            ID_arraza = 8,
                            ImageUrl = "\\images\\animalia\\felicia.jpg",
                            Izena = "Felicia the Flamboyant Flamingo",
                            Sarrera_data = new DateOnly(2022, 9, 15),
                            urte_betetzea = new DateOnly(2020, 1, 5)
                        },
                        new
                        {
                            ID = 9,
                            ID_arraza = 9,
                            ImageUrl = "\\images\\animalia\\percy.jpg",
                            Izena = "Percy the Playful Polar Bear",
                            Sarrera_data = new DateOnly(2020, 7, 22),
                            urte_betetzea = new DateOnly(2018, 10, 12)
                        },
                        new
                        {
                            ID = 10,
                            ID_arraza = 10,
                            ImageUrl = "\\images\\animalia\\penny.jpg",
                            Izena = "Penny the Perky Penguin",
                            Sarrera_data = new DateOnly(2023, 2, 28),
                            urte_betetzea = new DateOnly(2020, 8, 20)
                        },
                        new
                        {
                            ID = 11,
                            ID_arraza = 11,
                            ImageUrl = "\\images\\animalia\\milo.jpg",
                            Izena = "Milo the Mischievous Meerkat",
                            Sarrera_data = new DateOnly(2021, 12, 10),
                            urte_betetzea = new DateOnly(2019, 5, 3)
                        },
                        new
                        {
                            ID = 12,
                            ID_arraza = 12,
                            ImageUrl = "\\images\\animalia\\gracie.jpg",
                            Izena = "Gracie the Graceful Gibbon",
                            Sarrera_data = new DateOnly(2022, 6, 5),
                            urte_betetzea = new DateOnly(2019, 1, 18)
                        },
                        new
                        {
                            ID = 13,
                            ID_arraza = 7,
                            ImageUrl = "\\images\\animalia\\eric.jpg",
                            Izena = "Eric the Enthusiastic Elephant",
                            Sarrera_data = new DateOnly(2023, 4, 12),
                            urte_betetzea = new DateOnly(2020, 1, 30)
                        },
                        new
                        {
                            ID = 14,
                            ID_arraza = 8,
                            ImageUrl = "\\images\\animalia\\fiona.jpg",
                            Izena = "Fiona the Fancy Flamingo",
                            Sarrera_data = new DateOnly(2023, 7, 19),
                            urte_betetzea = new DateOnly(2021, 2, 10)
                        },
                        new
                        {
                            ID = 15,
                            ID_arraza = 13,
                            ImageUrl = "\\images\\animalia\\gerald.jpg",
                            Izena = "Gerald the Gentle Giraffe",
                            Sarrera_data = new DateOnly(2023, 8, 20),
                            urte_betetzea = new DateOnly(2020, 12, 5)
                        },
                        new
                        {
                            ID = 16,
                            ID_arraza = 14,
                            ImageUrl = "\\images\\animalia\\katie.jpg",
                            Izena = "Katie the Cuddly Koala",
                            Sarrera_data = new DateOnly(2024, 1, 15),
                            urte_betetzea = new DateOnly(2021, 5, 25)
                        },
                        new
                        {
                            ID = 17,
                            ID_arraza = 15,
                            ImageUrl = "\\images\\animalia\\manny.jpg",
                            Izena = "Manny the Merry Monkey",
                            Sarrera_data = new DateOnly(2024, 3, 1),
                            urte_betetzea = new DateOnly(2021, 9, 12)
                        },
                        new
                        {
                            ID = 18,
                            ID_arraza = 16,
                            ImageUrl = "\\images\\animalia\\zara.jpg",
                            Izena = "Zara the Zesty Zebra",
                            Sarrera_data = new DateOnly(2024, 2, 10),
                            urte_betetzea = new DateOnly(2021, 6, 25)
                        },
                        new
                        {
                            ID = 19,
                            ID_arraza = 17,
                            ImageUrl = "\\images\\animalia\\leo.jpg",
                            Izena = "Leo the Majestic Lion",
                            Sarrera_data = new DateOnly(2024, 3, 10),
                            urte_betetzea = new DateOnly(2021, 8, 25)
                        },
                        new
                        {
                            ID = 20,
                            ID_arraza = 17,
                            ImageUrl = "\\images\\animalia\\luna.jpg",
                            Izena = "Luna the Fierce Lioness",
                            Sarrera_data = new DateOnly(2024, 3, 15),
                            urte_betetzea = new DateOnly(2021, 9, 2)
                        },
                        new
                        {
                            ID = 21,
                            ID_arraza = 17,
                            ImageUrl = "\\images\\animalia\\max.jpg",
                            Izena = "Max the Mighty Lion",
                            Sarrera_data = new DateOnly(2024, 3, 20),
                            urte_betetzea = new DateOnly(2021, 9, 10)
                        },
                        new
                        {
                            ID = 22,
                            ID_arraza = 17,
                            ImageUrl = "\\images\\animalia\\lola.jpg",
                            Izena = "Lola the Lovely Lioness",
                            Sarrera_data = new DateOnly(2024, 3, 25),
                            urte_betetzea = new DateOnly(2021, 9, 18)
                        },
                        new
                        {
                            ID = 23,
                            ID_arraza = 17,
                            ImageUrl = "\\images\\animalia\\simba.jpg",
                            Izena = "Simba the Courageous Lion",
                            Sarrera_data = new DateOnly(2024, 3, 28),
                            urte_betetzea = new DateOnly(2021, 9, 22)
                        },
                        new
                        {
                            ID = 24,
                            ID_arraza = 1,
                            ImageUrl = "\\images\\animalia\\carlos.jpg",
                            Izena = "Carlos the Cheerful Chimpanzee",
                            Sarrera_data = new DateOnly(2024, 4, 1),
                            urte_betetzea = new DateOnly(2021, 10, 5)
                        },
                        new
                        {
                            ID = 25,
                            ID_arraza = 1,
                            ImageUrl = "\\images\\animalia\\chloe.jpg",
                            Izena = "Chloe the Charming Chimpanzee",
                            Sarrera_data = new DateOnly(2024, 4, 5),
                            urte_betetzea = new DateOnly(2021, 10, 10)
                        },
                        new
                        {
                            ID = 26,
                            ID_arraza = 1,
                            ImageUrl = "\\images\\animalia\\chip.jpg",
                            Izena = "Chip the Clever Chimpanzee",
                            Sarrera_data = new DateOnly(2024, 4, 10),
                            urte_betetzea = new DateOnly(2021, 10, 15)
                        },
                        new
                        {
                            ID = 27,
                            ID_arraza = 1,
                            ImageUrl = "\\images\\animalia\\charlotte.jpg",
                            Izena = "Charlotte the Curious Chimpanzee",
                            Sarrera_data = new DateOnly(2024, 4, 15),
                            urte_betetzea = new DateOnly(2021, 10, 20)
                        },
                        new
                        {
                            ID = 28,
                            ID_arraza = 1,
                            ImageUrl = "\\images\\animalia\\cooper.jpg",
                            Izena = "Cooper the Confident Chimpanzee",
                            Sarrera_data = new DateOnly(2024, 4, 20),
                            urte_betetzea = new DateOnly(2021, 10, 25)
                        },
                        new
                        {
                            ID = 29,
                            ID_arraza = 1,
                            ImageUrl = "\\images\\animalia\\cindy.jpg",
                            Izena = "Cindy the Cute Chimpanzee",
                            Sarrera_data = new DateOnly(2024, 4, 25),
                            urte_betetzea = new DateOnly(2021, 10, 30)
                        },
                        new
                        {
                            ID = 30,
                            ID_arraza = 1,
                            ImageUrl = "\\images\\animalia\\connor.jpg",
                            Izena = "Connor the Cuddly Chimpanzee",
                            Sarrera_data = new DateOnly(2024, 4, 30),
                            urte_betetzea = new DateOnly(2021, 11, 5)
                        },
                        new
                        {
                            ID = 31,
                            ID_arraza = 1,
                            ImageUrl = "\\images\\animalia\\cleo.jpg",
                            Izena = "Cleo the Creative Chimpanzee",
                            Sarrera_data = new DateOnly(2024, 5, 5),
                            urte_betetzea = new DateOnly(2021, 11, 10)
                        },
                        new
                        {
                            ID = 32,
                            ID_arraza = 10,
                            ImageUrl = "\\images\\animalia\\paul.jpg",
                            Izena = "Paul the Playful Penguin",
                            Sarrera_data = new DateOnly(2024, 4, 1),
                            urte_betetzea = new DateOnly(2021, 10, 5)
                        },
                        new
                        {
                            ID = 33,
                            ID_arraza = 10,
                            ImageUrl = "\\images\\animalia\\poppy.jpg",
                            Izena = "Poppy the Perky Penguin",
                            Sarrera_data = new DateOnly(2024, 4, 5),
                            urte_betetzea = new DateOnly(2021, 10, 10)
                        },
                        new
                        {
                            ID = 34,
                            ID_arraza = 10,
                            ImageUrl = "\\images\\animalia\\arturo.jpg",
                            Izena = "Arturo the Pensive Penguin",
                            Sarrera_data = new DateOnly(2024, 4, 10),
                            urte_betetzea = new DateOnly(2021, 10, 15)
                        },
                        new
                        {
                            ID = 35,
                            ID_arraza = 10,
                            ImageUrl = "\\images\\animalia\\pen.jpg",
                            Izena = "Pen the Polite Penguin",
                            Sarrera_data = new DateOnly(2024, 4, 15),
                            urte_betetzea = new DateOnly(2021, 10, 20)
                        },
                        new
                        {
                            ID = 36,
                            ID_arraza = 10,
                            ImageUrl = "\\images\\animalia\\pablo.jpg",
                            Izena = "Pablo the Playful Penguin",
                            Sarrera_data = new DateOnly(2024, 4, 20),
                            urte_betetzea = new DateOnly(2021, 10, 25)
                        },
                        new
                        {
                            ID = 37,
                            ID_arraza = 10,
                            ImageUrl = "\\images\\animalia\\polly.jpg",
                            Izena = "Polly the Prancing Penguin",
                            Sarrera_data = new DateOnly(2024, 4, 25),
                            urte_betetzea = new DateOnly(2021, 10, 30)
                        },
                        new
                        {
                            ID = 38,
                            ID_arraza = 10,
                            ImageUrl = "\\images\\animalia\\peter.jpg",
                            Izena = "Peter the Peaceful Penguin",
                            Sarrera_data = new DateOnly(2024, 4, 30),
                            urte_betetzea = new DateOnly(2021, 11, 5)
                        },
                        new
                        {
                            ID = 39,
                            ID_arraza = 10,
                            ImageUrl = "\\images\\animalia\\penelope.jpg",
                            Izena = "Penelope the Patient Penguin",
                            Sarrera_data = new DateOnly(2024, 5, 5),
                            urte_betetzea = new DateOnly(2021, 11, 10)
                        },
                        new
                        {
                            ID = 40,
                            ID_arraza = 10,
                            ImageUrl = "\\images\\animalia\\patrick.jpg",
                            Izena = "Patrick the Playful Penguin",
                            Sarrera_data = new DateOnly(2024, 5, 10),
                            urte_betetzea = new DateOnly(2021, 11, 15)
                        },
                        new
                        {
                            ID = 41,
                            ID_arraza = 10,
                            ImageUrl = "\\images\\animalia\\pippa.jpg",
                            Izena = "Pippa the Prankster Penguin",
                            Sarrera_data = new DateOnly(2024, 5, 15),
                            urte_betetzea = new DateOnly(2021, 11, 20)
                        },
                        new
                        {
                            ID = 42,
                            ID_arraza = 16,
                            ImageUrl = "\\images\\animalia\\sarita.jpg",
                            Izena = "Sarita the Zany Zebra",
                            Sarrera_data = new DateOnly(2024, 4, 5),
                            urte_betetzea = new DateOnly(2021, 10, 10)
                        },
                        new
                        {
                            ID = 43,
                            ID_arraza = 16,
                            ImageUrl = "\\images\\animalia\\ziggy.jpg",
                            Izena = "Ziggy the Zippy Zebra",
                            Sarrera_data = new DateOnly(2024, 4, 10),
                            urte_betetzea = new DateOnly(2021, 10, 15)
                        },
                        new
                        {
                            ID = 44,
                            ID_arraza = 2,
                            ImageUrl = "\\images\\animalia\\gus.jpg",
                            Izena = "Gus the Gentle Giant Gorilla",
                            Sarrera_data = new DateOnly(2024, 4, 1),
                            urte_betetzea = new DateOnly(2021, 10, 5)
                        },
                        new
                        {
                            ID = 45,
                            ID_arraza = 2,
                            ImageUrl = "\\images\\animalia\\greta.jpg",
                            Izena = "Greta the Gracious Gorilla",
                            Sarrera_data = new DateOnly(2024, 4, 5),
                            urte_betetzea = new DateOnly(2021, 10, 10)
                        },
                        new
                        {
                            ID = 46,
                            ID_arraza = 2,
                            ImageUrl = "\\images\\animalia\\greg.jpg",
                            Izena = "Greg the Gentle Gorilla",
                            Sarrera_data = new DateOnly(2024, 4, 10),
                            urte_betetzea = new DateOnly(2021, 10, 15)
                        },
                        new
                        {
                            ID = 47,
                            ID_arraza = 2,
                            ImageUrl = "\\images\\animalia\\gigi.jpg",
                            Izena = "Gigi the Gorgeous Gorilla",
                            Sarrera_data = new DateOnly(2024, 4, 15),
                            urte_betetzea = new DateOnly(2021, 10, 20)
                        },
                        new
                        {
                            ID = 48,
                            ID_arraza = 3,
                            ImageUrl = "\\images\\animalia\\rusty.jpg",
                            Izena = "Rusty the Radiant Red Panda",
                            Sarrera_data = new DateOnly(2024, 4, 1),
                            urte_betetzea = new DateOnly(2021, 10, 5)
                        },
                        new
                        {
                            ID = 49,
                            ID_arraza = 18,
                            ImageUrl = "\\images\\animalia\\tony.jpg",
                            Izena = "Tony the Terrific Tiger",
                            Sarrera_data = new DateOnly(2024, 4, 1),
                            urte_betetzea = new DateOnly(2021, 10, 5)
                        },
                        new
                        {
                            ID = 50,
                            ID_arraza = 18,
                            ImageUrl = "\\images\\animalia\\tara.jpg",
                            Izena = "Tara the Tremendous Tiger",
                            Sarrera_data = new DateOnly(2024, 4, 5),
                            urte_betetzea = new DateOnly(2021, 10, 10)
                        },
                        new
                        {
                            ID = 51,
                            ID_arraza = 18,
                            ImageUrl = "\\images\\animalia\\tim.jpg",
                            Izena = "Tim the Tenacious Tiger",
                            Sarrera_data = new DateOnly(2024, 4, 10),
                            urte_betetzea = new DateOnly(2021, 10, 15)
                        },
                        new
                        {
                            ID = 52,
                            ID_arraza = 18,
                            ImageUrl = "\\images\\animalia\\tess.jpg",
                            Izena = "Tess the Fearless Tiger",
                            Sarrera_data = new DateOnly(2024, 4, 15),
                            urte_betetzea = new DateOnly(2021, 10, 20)
                        },
                        new
                        {
                            ID = 53,
                            ID_arraza = 18,
                            ImageUrl = "\\images\\animalia\\tyler.jpg",
                            Izena = "Tyler the Triumphant Tiger",
                            Sarrera_data = new DateOnly(2024, 4, 20),
                            urte_betetzea = new DateOnly(2021, 10, 25)
                        },
                        new
                        {
                            ID = 54,
                            ID_arraza = 18,
                            ImageUrl = "\\images\\animalia\\tina.jpg",
                            Izena = "Tina the Tenacious Tiger",
                            Sarrera_data = new DateOnly(2024, 4, 25),
                            urte_betetzea = new DateOnly(2021, 10, 30)
                        });
                });

            modelBuilder.Entity("Zoo.Models.Arraza", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("Deskribapena")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("ID_lekua")
                        .HasColumnType("int");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Izena")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.HasIndex("ID_lekua");

                    b.ToTable("Arrazak");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            Deskribapena = "Donec ante enim, imperdiet non metus a, aliquet fermentum tortor. Etiam sem nunc, ornare id dignissim non, congue at nulla. Integer semper leo nisl, ac tincidunt libero aliquam id. Morbi quis ornare eros. Nunc at ultricies mi. Aliquam vitae bibendum metus. Aenean venenatis cursus sapien. Vivamus feugiat egestas urna.",
                            ID_lekua = 5,
                            ImageUrl = "\\images\\arraza\\chimpanzee1.jpg",
                            Izena = "Txinpantze"
                        },
                        new
                        {
                            ID = 2,
                            Deskribapena = "Donec ante enim, imperdiet non metus a, aliquet fermentum tortor. Etiam sem nunc, ornare id dignissim non, congue at nulla. Integer semper leo nisl, ac tincidunt libero aliquam id. Morbi quis ornare eros. Nunc at ultricies mi. Aliquam vitae bibendum metus. Aenean venenatis cursus sapien. Vivamus feugiat egestas urna.",
                            ID_lekua = 5,
                            ImageUrl = "\\images\\arraza\\gorilla1.jpg",
                            Izena = "Gorila"
                        },
                        new
                        {
                            ID = 3,
                            Deskribapena = "Donec ante enim, imperdiet non metus a, aliquet fermentum tortor. Etiam sem nunc, ornare id dignissim non, congue at nulla. Integer semper leo nisl, ac tincidunt libero aliquam id. Morbi quis ornare eros. Nunc at ultricies mi. Aliquam vitae bibendum metus. Aenean venenatis cursus sapien. Vivamus feugiat egestas urna.",
                            ID_lekua = 4,
                            ImageUrl = "\\images\\arraza\\red-panda1.jpg",
                            Izena = "Panda Gorria"
                        },
                        new
                        {
                            ID = 4,
                            Deskribapena = "Donec ante enim, imperdiet non metus a, aliquet fermentum tortor. Etiam sem nunc, ornare id dignissim non, congue at nulla. Integer semper leo nisl, ac tincidunt libero aliquam id. Morbi quis ornare eros. Nunc at ultricies mi. Aliquam vitae bibendum metus. Aenean venenatis cursus sapien. Vivamus feugiat egestas urna.",
                            ID_lekua = 1,
                            ImageUrl = "\\images\\arraza\\kangaroo1.jpg",
                            Izena = "Kanguru"
                        },
                        new
                        {
                            ID = 5,
                            Deskribapena = "Donec ante enim, imperdiet non metus a, aliquet fermentum tortor. Etiam sem nunc, ornare id dignissim non, congue at nulla. Integer semper leo nisl, ac tincidunt libero aliquam id. Morbi quis ornare eros. Nunc at ultricies mi. Aliquam vitae bibendum metus. Aenean venenatis cursus sapien. Vivamus feugiat egestas urna.",
                            ID_lekua = 5,
                            ImageUrl = "\\images\\arraza\\sloth1.jpg",
                            Izena = "Nagi"
                        },
                        new
                        {
                            ID = 6,
                            Deskribapena = "Donec ante enim, imperdiet non metus a, aliquet fermentum tortor. Etiam sem nunc, ornare id dignissim non, congue at nulla. Integer semper leo nisl, ac tincidunt libero aliquam id. Morbi quis ornare eros. Nunc at ultricies mi. Aliquam vitae bibendum metus. Aenean venenatis cursus sapien. Vivamus feugiat egestas urna.",
                            ID_lekua = 2,
                            ImageUrl = "\\images\\arraza\\artic-fox1.jpg",
                            Izena = "Azeri artikoa"
                        },
                        new
                        {
                            ID = 7,
                            Deskribapena = "Donec ante enim, imperdiet non metus a, aliquet fermentum tortor. Etiam sem nunc, ornare id dignissim non, congue at nulla. Integer semper leo nisl, ac tincidunt libero aliquam id. Morbi quis ornare eros. Nunc at ultricies mi. Aliquam vitae bibendum metus. Aenean venenatis cursus sapien. Vivamus feugiat egestas urna.",
                            ID_lekua = 3,
                            ImageUrl = "\\images\\arraza\\elephant1.jpg",
                            Izena = "Elefante"
                        },
                        new
                        {
                            ID = 8,
                            Deskribapena = "Donec ante enim, imperdiet non metus a, aliquet fermentum tortor. Etiam sem nunc, ornare id dignissim non, congue at nulla. Integer semper leo nisl, ac tincidunt libero aliquam id. Morbi quis ornare eros. Nunc at ultricies mi. Aliquam vitae bibendum metus. Aenean venenatis cursus sapien. Vivamus feugiat egestas urna.",
                            ID_lekua = 4,
                            ImageUrl = "\\images\\arraza\\flamingo1.jpg",
                            Izena = "Flamenko"
                        },
                        new
                        {
                            ID = 9,
                            Deskribapena = "Donec ante enim, imperdiet non metus a, aliquet fermentum tortor. Etiam sem nunc, ornare id dignissim non, congue at nulla. Integer semper leo nisl, ac tincidunt libero aliquam id. Morbi quis ornare eros. Nunc at ultricies mi. Aliquam vitae bibendum metus. Aenean venenatis cursus sapien. Vivamus feugiat egestas urna.",
                            ID_lekua = 2,
                            ImageUrl = "\\images\\arraza\\polar-bear1.jpg",
                            Izena = "Hartz zuri"
                        },
                        new
                        {
                            ID = 10,
                            Deskribapena = "Donec ante enim, imperdiet non metus a, aliquet fermentum tortor. Etiam sem nunc, ornare id dignissim non, congue at nulla. Integer semper leo nisl, ac tincidunt libero aliquam id. Morbi quis ornare eros. Nunc at ultricies mi. Aliquam vitae bibendum metus. Aenean venenatis cursus sapien. Vivamus feugiat egestas urna.",
                            ID_lekua = 2,
                            ImageUrl = "\\images\\arraza\\penguin1.jpg",
                            Izena = "Pinguino"
                        },
                        new
                        {
                            ID = 11,
                            Deskribapena = "Donec ante enim, imperdiet non metus a, aliquet fermentum tortor. Etiam sem nunc, ornare id dignissim non, congue at nulla. Integer semper leo nisl, ac tincidunt libero aliquam id. Morbi quis ornare eros. Nunc at ultricies mi. Aliquam vitae bibendum metus. Aenean venenatis cursus sapien. Vivamus feugiat egestas urna.",
                            ID_lekua = 3,
                            ImageUrl = "\\images\\arraza\\meerkat1.jpg",
                            Izena = "Surikata"
                        },
                        new
                        {
                            ID = 12,
                            Deskribapena = "Donec ante enim, imperdiet non metus a, aliquet fermentum tortor. Etiam sem nunc, ornare id dignissim non, congue at nulla. Integer semper leo nisl, ac tincidunt libero aliquam id. Morbi quis ornare eros. Nunc at ultricies mi. Aliquam vitae bibendum metus. Aenean venenatis cursus sapien. Vivamus feugiat egestas urna.",
                            ID_lekua = 5,
                            ImageUrl = "\\images\\arraza\\gibbon1.jpg",
                            Izena = "Giboi"
                        },
                        new
                        {
                            ID = 13,
                            Deskribapena = "Donec ante enim, imperdiet non metus a, aliquet fermentum tortor. Etiam sem nunc, ornare id dignissim non, congue at nulla. Integer semper leo nisl, ac tincidunt libero aliquam id. Morbi quis ornare eros. Nunc at ultricies mi. Aliquam vitae bibendum metus. Aenean venenatis cursus sapien. Vivamus feugiat egestas urna.",
                            ID_lekua = 3,
                            ImageUrl = "\\images\\arraza\\giraffe1.jpg",
                            Izena = "Jirafa"
                        },
                        new
                        {
                            ID = 14,
                            Deskribapena = "Donec ante enim, imperdiet non metus a, aliquet fermentum tortor. Etiam sem nunc, ornare id dignissim non, congue at nulla. Integer semper leo nisl, ac tincidunt libero aliquam id. Morbi quis ornare eros. Nunc at ultricies mi. Aliquam vitae bibendum metus. Aenean venenatis cursus sapien. Vivamus feugiat egestas urna.",
                            ID_lekua = 1,
                            ImageUrl = "\\images\\arraza\\koala1.jpg",
                            Izena = "Koala"
                        },
                        new
                        {
                            ID = 15,
                            Deskribapena = "Donec ante enim, imperdiet non metus a, aliquet fermentum tortor. Etiam sem nunc, ornare id dignissim non, congue at nulla. Integer semper leo nisl, ac tincidunt libero aliquam id. Morbi quis ornare eros. Nunc at ultricies mi. Aliquam vitae bibendum metus. Aenean venenatis cursus sapien. Vivamus feugiat egestas urna.",
                            ID_lekua = 5,
                            ImageUrl = "\\images\\arraza\\monkey1.jpg",
                            Izena = "Tximino"
                        },
                        new
                        {
                            ID = 16,
                            Deskribapena = "Donec ante enim, imperdiet non metus a, aliquet fermentum tortor. Etiam sem nunc, ornare id dignissim non, congue at nulla. Integer semper leo nisl, ac tincidunt libero aliquam id. Morbi quis ornare eros. Nunc at ultricies mi. Aliquam vitae bibendum metus. Aenean venenatis cursus sapien. Vivamus feugiat egestas urna.",
                            ID_lekua = 3,
                            ImageUrl = "\\images\\arraza\\zebra1.jpg",
                            Izena = "Zebra"
                        },
                        new
                        {
                            ID = 17,
                            Deskribapena = "Donec ante enim, imperdiet non metus a, aliquet fermentum tortor. Etiam sem nunc, ornare id dignissim non, congue at nulla. Integer semper leo nisl, ac tincidunt libero aliquam id. Morbi quis ornare eros. Nunc at ultricies mi. Aliquam vitae bibendum metus. Aenean venenatis cursus sapien. Vivamus feugiat egestas urna.",
                            ID_lekua = 3,
                            ImageUrl = "\\images\\arraza\\lion1.jpg",
                            Izena = "Lehoi"
                        },
                        new
                        {
                            ID = 18,
                            Deskribapena = "Donec ante enim, imperdiet non metus a, aliquet fermentum tortor. Etiam sem nunc, ornare id dignissim non, congue at nulla. Integer semper leo nisl, ac tincidunt libero aliquam id. Morbi quis ornare eros. Nunc at ultricies mi. Aliquam vitae bibendum metus. Aenean venenatis cursus sapien. Vivamus feugiat egestas urna.",
                            ID_lekua = 3,
                            ImageUrl = "\\images\\arraza\\tiger1.jpg",
                            Izena = "Tigre"
                        });
                });

            modelBuilder.Entity("Zoo.Models.Lekua", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("Deskribapena")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Izena")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("Lekuak");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            Deskribapena = "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
                            Izena = "Australia"
                        },
                        new
                        {
                            ID = 2,
                            Deskribapena = "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
                            Izena = "Artikoa"
                        },
                        new
                        {
                            ID = 3,
                            Deskribapena = "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
                            Izena = "Sabana"
                        },
                        new
                        {
                            ID = 4,
                            Deskribapena = "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
                            Izena = "Asia"
                        },
                        new
                        {
                            ID = 5,
                            Deskribapena = "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
                            Izena = "Baso Tropikala"
                        });
                });

            modelBuilder.Entity("Zoo.Models.Bezero", b =>
                {
                    b.HasBaseType("Microsoft.AspNetCore.Identity.IdentityUser");

                    b.Property<string>("Abizena")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Izena")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasDiscriminator().HasValue("Bezero");
                });

            modelBuilder.Entity("Zoo.Models.Langile", b =>
                {
                    b.HasBaseType("Microsoft.AspNetCore.Identity.IdentityUser");

                    b.Property<string>("Abizena")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Izena")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Postua")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Turnoa")
                        .HasColumnType("nvarchar(max)");

                    b.ToTable("AspNetUsers", t =>
                        {
                            t.Property("Abizena")
                                .HasColumnName("Langile_Abizena");

                            t.Property("Izena")
                                .HasColumnName("Langile_Izena");
                        });

                    b.HasDiscriminator().HasValue("Langile");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Zoo.Models.Animalia", b =>
                {
                    b.HasOne("Zoo.Models.Arraza", "Arraza")
                        .WithMany()
                        .HasForeignKey("ID_arraza");

                    b.Navigation("Arraza");
                });

            modelBuilder.Entity("Zoo.Models.Arraza", b =>
                {
                    b.HasOne("Zoo.Models.Lekua", "Lekua")
                        .WithMany()
                        .HasForeignKey("ID_lekua");

                    b.Navigation("Lekua");
                });
#pragma warning restore 612, 618
        }
    }
}
